# Generated by Django 5.1.2 on 2024-11-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
